### ISSUE TITLE
Can it support with GridLayoutManager

### ISSUE THREAD

**Issue by UltramanTIGA** [Faltenreich/SkeletonLayout#1]
Hi!
The library you written is very great and simple to use,I'm very like it!
I have a question.It works well with LinearLayoutManager,Then can it support the RecyclerView with GridLayoutManager?

**Comment by Faltenreich** [comment]
Hello @UltramanTIGA, thank you for your positive feedback - it is much appreciated!
SkeletonLayout does support the GridLayoutManager and any other LayoutManager, since it reuses the one from the original RecyclerView. :)

**Comment by UltramanTIGA** [comment]
Thanks for reply!
I set GridLayoutManager with 2 column in RecyclerView,And then apply skeleton to show,But the skeleton only show 1 column just same as LinearLayout.Below is my code:
`val imageSize = (ScreenUtils.getScreenWidth() - 4 * SizeUtils.dp2px(8f)) / 2
    mAdapter = ImageGridAdapter(imageSize)

    list.layoutManager = GridLayoutManager(mContext,2)
    list.adapter = mAdapter
    skeleton = list.applySkeleton(R.layout.list_item).apply { showSkeleton() }`
Is there any other options should be added in the adapter of RecyclerView ?

**Comment by UltramanTIGA** [comment]
Thanks for reply!
I have found that the problem come from the ImageGridAdapter,It extends library
github.com/CymChad/BaseRecyclerViewAdapterHelper.
Maybe it has some code that make the RecyclerView show skeleton incorrectly.
