### ISSUE TITLE
RecyclerView background not working

### ISSUE THREAD

**Issue by KrT996** [Faltenreich/SkeletonLayout#19]
It doesn’t take effect in recyclerView list item background (Background turns transparent).  It only effective for inner views.

**Comment by Faltenreich** [comment]
Could you please provide a small sample with the actual and the expected output in order to understand and reproduce your isse correctly?

**Comment by JavaYank** [comment]
i have same problem

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="@dimen/_200sdp"
    android:layout_height="@dimen/_70sdp"
    android:background="@drawable/blue_corner_radius"
    android:gravity="center_vertical"
    android:orientation="horizontal">

        <ImageView
            android:id="@+id/img_icon"
            android:layout_width="@dimen/_36sdp"
            android:layout_height="@dimen/_36sdp"
            android:layout_marginStart="@dimen/_16sdp"
            android:layout_marginTop="@dimen/_16sdp"
            android:layout_marginEnd="@dimen/_10sdp"
            android:layout_marginBottom="@dimen/_16sdp"
            android:contentDescription="@string/content_description"
            android:scaleType="fitXY"
            android:src="@mipmap/ic_usd" />
</LinearLayout>
```

background of LinearLayout doesn’t work


![image](https://user-images.githubusercontent.com/29397168/89735227-64c94a00-da7a-11ea-8acf-454f715f5a29.png)


```
skeleton = SkeletonLayoutUtils.applySkeleton(recycler, R.layout.item_skeleton, 5);
skeleton.setMaskColor(Color.GREEN);
skeleton.setMaskCornerRadius(60f);
skeleton.showSkeleton();
```

**Comment by Faltenreich** [comment]
This behavior is intended, since the SkeleteonLayout masks every View with the shimmer effect and skips ViewGroups. Keeping (background) colors would clutter the layout and is therefore not part of the library. I hope I understood your issue correctly and this answer makes sense for you.
