### ISSUE TITLE
Actually this library have support ?

### ISSUE THREAD

**Issue by ederdoski** [Faltenreich/SkeletonLayout#39]
Hi ! i really like this library but i saw the last Release was in oct 2020, so, i have question about the support of this library, is working? o this proyect was deprecated? thx so much for your time and your help !

**Comment by Faltenreich** [comment]
Thank you for your question! The project is active and working and there should be nothing gamebreaking preventing you from using this library in your projects. The open issues may not have been touched for a while but are not yet forgotten and of course you are welcome to create a pull request that I am looking forward to review and merge. :)
