### ISSUE TITLE
Redraw skeleton when views visibility changed

### ISSUE THREAD

**Issue by eypibee** [Faltenreich/SkeletonLayout#8]
Hi @Faltenreich . Whenever there are no items to be displayed in my **RecyclerView**, I am showing a **TextView** saying it has no content. Unluckily, when I press a button to refresh the adapter and it has now content, the skeleton of the **TextView** is still remains. 

 Is it possible to redraw the skeleton ?

**Comment by Faltenreich** [comment]
Are you using the applySkeleton() or createSkeleton() method? The skeleton should normally be simply enabled or disabled by calling showSkeleton() or showOriginal(). Maybe you are calling showSkeleton() when refreshing your original adapter?

**Comment by Faltenreich** [comment]
I suppose you are using applySkeleton() directly on the RecyclerView. To redraw the skeleton, you simply have to create a new skeleton by calling applySkeleton() again (with the corresponding layout resource identifier).

**Comment by Faltenreich** [comment]
I will close this issue due to inactivity. Feel free to reopen it if there is more feedback to come.
